version: '3'

services:
    client:
        image: "garyclarke/ghactions-client"
        mem_limit: 128m
        hostname: client
#        environment:
#            - WDS_SOCKET_PORT=0
    api:
        image: "garyclarke/ghactions-server"
        mem_limit: 128m
        hostname: api
        environment:
            - REDIS_HOST=$REDIS_HOST
            - REDIS_PORT=$REDIS_PORT
            - PGUSER=$PGUSER
            - PGHOST=$PGHOST
            - PGDATABASE=$PGDATABASE
            - PGPASSWORD=$PGPASSWORD
            - PGPORT=$PGPORT
    worker:
        image: "garyclarke/ghactions-worker"
        mem_limit: 128m
        hostname: worker
        environment:
            - REDIS_HOST=$REDIS_HOST
            - REDIS_PORT=$REDIS_PORT
    nginx:
        image: "garyclarke/ghactions-nginx"
        mem_limit: 128m
        hostname: nginx
        ports:
            - "80:80"
#        depends_on:
#            - api
#            - client