name: FibMultiDocker
on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: docker build -t garyclarke/client-test -f ./client/Dockerfile.dev ./client
            - run: docker run -e CI=true garyclarke/client-test npm test
            - run: docker build -t garyclarke/ghactions-client ./client
            - run: docker build -t garyclarke/ghactions-nginx ./nginx
            - run: docker build -t garyclarke/ghactions-server ./server
            - run: docker build -t garyclarke/ghactions-worker ./worker
            - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            - run: docker push garyclarke/ghactions-client
            - run: docker push garyclarke/ghactions-nginx
            - run: docker push garyclarke/ghactions-server
            - run: docker push garyclarke/ghactions-worker

            - name: Generate deployment package
              run: zip -r deploy.zip . -x '*.git*'

            - name: Deploy to EB
              uses: einaregilsson/beanstalk-deploy@v18
              with:
                  aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
                  aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
                  application_name: fib-docker
                  environment_name: Fibdocker-env
                  existing_bucket_name: elasticbeanstalk-eu-west-1-234290944523
                  region: eu-west-1
                  version_label: ${{ github.sha }}
                  deployment_package: deploy.zip
